format = "$character"
right_format = "$directory$python$git_branch"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "blue"

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
disabled = true

[python]
format = "[\\($virtualenv\\) ]($style)"
style = "yellow"

[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](red)"
